import { test, expect } from "@playwright/test";
import { compare } from "odiff-bin";
import fs from "node:fs";
import path from "node:path";

const BASELINE = "tests/visual/__baseline__";
const ACTUAL = "tests/visual/__actual__";
const DIFF = "tests/visual/__diff__";

// Screenshot the page and compare against a committed baseline with odiff.
// First run for a given name writes the baseline (and passes with a note), so
// baselines are generated by running the suite once, then committed.
export async function visualCheck(
  page: import("@playwright/test").Page,
  name: string,
): Promise<void> {
  for (const d of [BASELINE, ACTUAL, DIFF]) fs.mkdirSync(d, { recursive: true });
  const actual = path.join(ACTUAL, `${name}.png`);
  const baseline = path.join(BASELINE, `${name}.png`);
  const diff = path.join(DIFF, `${name}.png`);

  await page.screenshot({
    path: actual,
    fullPage: true,
    animations: "disabled",
    // The TOC's current-heading highlight is set by a client IntersectionObserver,
    // so which item is active is timing-dependent across runs. Mask the right-hand
    // TOC out of the diff to keep visual regression stable.
    mask: [page.locator(".right-sidebar")],
  });

  if (!fs.existsSync(baseline)) {
    fs.copyFileSync(actual, baseline);
    test.info().annotations.push({ type: "baseline-created", description: name });
    return;
  }

  const result = await compare(baseline, actual, diff, {
    antialiasing: true,
    threshold: 0.1,
  });
  expect(
    result.match,
    result.match ? undefined : `visual diff in "${name}": ${JSON.stringify(result)} (see ${diff})`,
  ).toBe(true);
}
